/*
 * Copyright(c) Red Hat Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//lint:file-ignore SA1019 Ignore all deprecated code, it's generated
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dp_cni_syncer.proto

package dpcnisyncer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteNetDevReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNetDevReq) Reset()         { *m = DeleteNetDevReq{} }
func (m *DeleteNetDevReq) String() string { return proto.CompactTextString(m) }
func (*DeleteNetDevReq) ProtoMessage()    {}
func (*DeleteNetDevReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9ab154255673e38, []int{0}
}

func (m *DeleteNetDevReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNetDevReq.Unmarshal(m, b)
}
func (m *DeleteNetDevReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNetDevReq.Marshal(b, m, deterministic)
}
func (m *DeleteNetDevReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNetDevReq.Merge(m, src)
}
func (m *DeleteNetDevReq) XXX_Size() int {
	return xxx_messageInfo_DeleteNetDevReq.Size(m)
}
func (m *DeleteNetDevReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNetDevReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNetDevReq proto.InternalMessageInfo

func (m *DeleteNetDevReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteNetDevResp struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNetDevResp) Reset()         { *m = DeleteNetDevResp{} }
func (m *DeleteNetDevResp) String() string { return proto.CompactTextString(m) }
func (*DeleteNetDevResp) ProtoMessage()    {}
func (*DeleteNetDevResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9ab154255673e38, []int{1}
}

func (m *DeleteNetDevResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNetDevResp.Unmarshal(m, b)
}
func (m *DeleteNetDevResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNetDevResp.Marshal(b, m, deterministic)
}
func (m *DeleteNetDevResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNetDevResp.Merge(m, src)
}
func (m *DeleteNetDevResp) XXX_Size() int {
	return xxx_messageInfo_DeleteNetDevResp.Size(m)
}
func (m *DeleteNetDevResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNetDevResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNetDevResp proto.InternalMessageInfo

func (m *DeleteNetDevResp) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteNetDevReq)(nil), "dpcnisyncer.DeleteNetDevReq")
	proto.RegisterType((*DeleteNetDevResp)(nil), "dpcnisyncer.DeleteNetDevResp")
}

func init() {
	proto.RegisterFile("dp_cni_syncer.proto", fileDescriptor_f9ab154255673e38)
}

var fileDescriptor_f9ab154255673e38 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x29, 0x88, 0x4f,
	0xce, 0xcb, 0x8c, 0x2f, 0xae, 0xcc, 0x4b, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4e, 0x29, 0x48, 0xce, 0xcb, 0x84, 0x08, 0x29, 0xa9, 0x72, 0xf1, 0xbb, 0xa4, 0xe6, 0xa4,
	0x96, 0xa4, 0xfa, 0xa5, 0x96, 0xb8, 0xa4, 0x96, 0x05, 0xa5, 0x16, 0x0a, 0x09, 0x71, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x2a, 0x5c, 0x02,
	0xa8, 0xca, 0x8a, 0x0b, 0x84, 0x04, 0xb8, 0x98, 0x8b, 0x52, 0x4b, 0xc0, 0xca, 0x58, 0x83, 0x40,
	0x4c, 0xa3, 0x20, 0x2e, 0x36, 0x88, 0xbc, 0x90, 0x07, 0x17, 0xa7, 0x4b, 0x6a, 0x0e, 0x94, 0x23,
	0xa3, 0x87, 0x64, 0xa3, 0x1e, 0x9a, 0x75, 0x52, 0xb2, 0x78, 0x64, 0x8b, 0x0b, 0x9c, 0x5c, 0xa2,
	0x9c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x33, 0xf3, 0x4a, 0x52,
	0x73, 0xf4, 0x13, 0xd3, 0x2a, 0x52, 0x0a, 0x74, 0x0b, 0x72, 0x4a, 0xd3, 0x33, 0xf3, 0x8a, 0x75,
	0xd3, 0xf2, 0x8b, 0x74, 0xb3, 0x4b, 0x93, 0x52, 0x8b, 0xf2, 0x52, 0x4b, 0x52, 0x8b, 0xc1, 0x4a,
	0x8a, 0xf2, 0x12, 0x73, 0xf4, 0x91, 0x8c, 0x4d, 0x62, 0x03, 0x7b, 0xdd, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x57, 0xca, 0xf4, 0x11, 0x01, 0x00, 0x00,
}
