@startuml

skinparam noteBorderColor Black
skinparam noteBorderThickness 1
skinparam noteBackgroundColor Yellow
skinparam legendBackgroundColor WhiteSmoke

skinparam sequence {
	BoxBorderColor Black
	BoxFontSize 20

	ArrowColor Black
	ArrowThickness 1

	ActorBorderColor Black
	ActorBorderThickness 3
	ActorBackgroundColor Business
	ActorFontSize 15

	ParticipantBorderColor Black
	ParticipantBorderThickness 1
	ParticipantBackgroundColor Business
	ParticipantFontSize 15

	LifeLineBorderColor Black
	LifeLineBorderThickness 1
	LifeLineBackgroundColor LightGray
}

legend top right
|= |= Legend |
|<back:LightBlue>   </back>| Participants from this project - Device Plugin and CNI |
|<back:Dodgerblue>   </back>| Threads within Device Plugin |
|<back:Business>   </back>| Participants external to this project |
|<back:Turquoise>   </back>| Code waits, listening on socket |
|<back:Yellow>   </back>| Notes |
endlegend

actor "User"
participant "Linux"
participant "Kubelet"
box "Device Plugin" #LightBlue
	participant "DP Main Thread" #dodgerblue
	participant "DP UDS Server Thread" #dodgerblue
end box
participant "CNI" #LightBlue
participant "Pod/CNDP App"

== Initialization ==
autonumber

"User" -> "Kubelet": network attachment definition (CNI config)
"User" -> "DP Main Thread": deploy
activate "DP Main Thread"

"DP Main Thread" -> "DP Main Thread": config.json
"DP Main Thread" -> "Linux": create log file
"DP Main Thread" -> "Linux" : Check host for requirements
"DP Main Thread" -> "Linux": net.Interfaces()

activate "DP Main Thread" #DarkGray
note right #DarkGray: <color #White>discover resources</color>

"Linux" --> "DP Main Thread": interface list
"DP Main Thread" -> "Linux": ethtool.DriverName()

activate "DP Main Thread" #SlateGray
note right #SlateGray: <color #White>loop interfaces, build device list</color>

"Linux" --> "DP Main Thread": driver

deactivate "DP Main Thread"

autonumber stop
"DP Main Thread" [hidden]-> "DP Main Thread"
autonumber resume

deactivate "DP Main Thread"

"DP Main Thread" -> "Linux" : cycle devices (netlink up/down)
"DP Main Thread" -> "DP Main Thread": start GRPC
"DP Main Thread" -> "Kubelet": GRPC: register
"DP Main Thread" -> "Kubelet": GRPC: device list

deactivate "DP Main Thread"

== Pod Creation ==
autonumber

"User" -> "Kubelet": create pod
"Kubelet" -> "DP Main Thread": GRPC: Allocate(ifname)
activate "DP Main Thread"

"DP Main Thread" -> "Linux": net.if_nametoindex(ifname)
"Linux" --> "DP Main Thread": if_index
"DP Main Thread" -> "Linux": bpf.xsk_setup_xdp_prog(if_index)
"Linux" --> "DP Main Thread": XSK file descriptor

"DP Main Thread" -> "DP Main Thread": create UDS
"DP Main Thread" -> "DP UDS Server Thread" ** : create & start UDS server
"DP Main Thread" -> "DP UDS Server Thread" : ifname, XSK FD, UDS filepath

hnote over "DP UDS Server Thread" #Turquoise
	  listen for
	  connection
endhnote

"DP Main Thread" --> "Kubelet": GRPC: AllocateResponse(UDS mount path, pod env vars)
deactivate "DP Main Thread"

autonumber stop
"Kubelet" -[#Red]>> "Pod/CNDP App" : <color:Red>Kubelet starts creating the pod around now
autonumber resume

"Kubelet" -> "CNI" : cmdAdd(ifname, namespace, config)
activate "CNI"
"CNI" -> "CNI" : cni.IPAM
"CNI" -> "Linux" : ethtool filters


"CNI" -> "Pod/CNDP App" : place interface in pod netns
"CNI" -> "Kubelet" : return 0

deactivate "CNI"

autonumber stop

== Pod Running ==

"Kubelet" -> "Pod/CNDP App" : start pod
"Pod/CNDP App" -> "Pod/CNDP App" : application start
activate "Pod/CNDP App"

"Pod/CNDP App" -> "DP UDS Server Thread": /connect,hostname
note right
	CNDP application starts
	UDS handshake begins
end note
activate "DP UDS Server Thread"
"DP UDS Server Thread" -> "Kubelet": podresources.ListPodResourcesRequest()
"Kubelet" --> "DP UDS Server Thread": podresources.ListPodResourcesResponse()
"DP UDS Server Thread" -> "DP UDS Server Thread": validate hostname against ifname
"DP UDS Server Thread" --> "Pod/CNDP App": /host_ok
deactivate "DP UDS Server Thread"
hnote over "DP UDS Server Thread" #Turquoise
	listen for
	request
end note

"Pod/CNDP App" -> "DP UDS Server Thread": /xsk_map_fd,ifname
activate "DP UDS Server Thread"
"DP UDS Server Thread" -> "DP UDS Server Thread": FD for ifname
"DP UDS Server Thread" --> "Pod/CNDP App": /fd_ack,FD
deactivate "DP UDS Server Thread"

hnote over "DP UDS Server Thread" #Turquoise
	listen for
	request
endhnote

"Pod/CNDP App" -> "DP UDS Server Thread": /config_busy_poll,FD
activate "DP UDS Server Thread"
"DP UDS Server Thread" -> "Linux" : bpf.setsockopt(FD, BUSY_POLL)
"Linux" --> "DP UDS Server Thread" : return 0
"DP UDS Server Thread" --> "Pod/CNDP App": /config_busy_poll_ack
deactivate "DP UDS Server Thread"

hnote over "DP UDS Server Thread" #Turquoise
	listen for
	request
endhnote

"Pod/CNDP App" -> "DP UDS Server Thread": /fin
activate "DP UDS Server Thread"
"DP UDS Server Thread" --> "Pod/CNDP App": /fin_ack
"Pod/CNDP App" [hidden]-> "Pod/CNDP App"
note left: UDS handshake ends
deactivate "DP UDS Server Thread"

destroy "DP UDS Server Thread"

== Pod Deletion ==
autonumber

"User" -> "Kubelet": delete pod
"Kubelet" -> "Pod/CNDP App" : stop pod
deactivate "Pod/CNDP App"
"Kubelet" -> "CNI" : cmdDel(ifname, config)
activate "CNI"
"CNI" -> "Pod/CNDP App" : interface from pod to host netns
"Pod/CNDP App" --> "CNI" : interface
"CNI" -> "CNI" : clear IPAM
"CNI" -> "Linux": net.if_nametoindex(ifname)
"Linux" --> "CNI": if_index
"CNI" -> "Linux": bpf.set_link_xdp_fd(if_index, -1)
"Linux" --> "CNI": return 0

"CNI" -> "Linux" : clear ethtool filters
"CNI" --> "Kubelet": return 0
deactivate "CNI"

"Kubelet" -> "Pod/CNDP App" : delete pod
deactivate "Pod/CNDP App"

@enduml
